### ISSUE TITLE
Feat: 유저가 주소를 선택한다.

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#115]
### 기능 설명
- 선택한 주소가 배달 가능 한 주소인지 확인
- 배달 가능한 주소의 직선거리 파악 후 배달료 책정

### To-Do
- [x] 좌표간 거리 계산
- [x] 좌표가 구역 내에 있는지 여부 확인
- [x] 거리에 따른 배달료 가져오기
