### ISSUE TITLE
Feat: 유저가 장바구니를 확인한다

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#124]
### 기능 설명
유저가 장바구니에 들어갔을 때 메뉴 품절 여부, 총 주문 금액(품절 메뉴 제외)을 확인할 수 있도록 클라이언트가 보낸 정보를 토대로 데이터를 반환하는 API

### To-Do
- [x] 주문 유효성 체크(메뉴 유효성, 옵션 유효성, 주소 유효성)
- [x] 메뉴 품절 여부 체크
- [x] 품절이 되지 않은 메뉴만 주문 금액 계산
- [x] 배달 가능 주소 여부 체크 -> 주소 유효성 체크시 할 예정
- [x] 배달비 계산(최소 주문 금액, 거리, 할증)
- [x] 품절여부, 주문금액, 배달가능 여부를 json 객체로 리턴
