### ISSUE TITLE
Feat: 주문 내역 조회 수정

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#142]
### 기능 설명
주문내역 response 데이터 수정

### To-Do
- [x] 유저번호 추출
- [x] 유저번호를 기반으로 주문내역 가져오기
- [x] `order_detail`을 기반으로 가게별 주문 금액 계산
- [x] 식당별 메뉴이름 1개, 주문 수량, 주문 금액  return
