### ISSUE TITLE
Feat: 수정사항 해결하기

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#177]
### 기능 설명
현재 발견된 수저사항들 수정하기

### To-Do
- [x] 결제 방식 order-view에 보내주기
- [x] order-list 사진 url 변경
- [x] 결제 방식에 따라 order 로직 변경
- [x] cart-check에서 메뉴,옵션 뿐 아니라 restaurant 상태 점검
- [x] 결제시 메뉴, 식당 status 점검해서 자동거절
- [x] 주문내역에서 주문실패(300003) 제외
