### ISSUE TITLE
Feat: 사용자 주소 조회 기능 API를 개발한다.

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#25]
### 기능 설명
사용자 인증 토큰을 통해 사용자의 주소를 리턴하는 API

### To-Do
- [x] 토큰을 통해 사용자 검증
- [x] 주소 테이블에서 사용자 주소 조회
- [ ] 주소가 유무에 따른 데이터 전송
