### ISSUE TITLE
Feat: 레스토랑 소개 및 메뉴정보 가져오기

### ISSUE THREAD

**Issue by KangJeongHo1** [OZ-Coding-School/oz_02_collabo-005-BE#36]
### 기능 설명
레스토랑 사진, 메뉴 그룹, 메뉴 정보를 가져온다

### To-Do
- [ ] 레스토랑에 대한 정보 가져오기
- [ ] 메뉴 그룹에 대한 정보 가져오기
- [ ] 메뉴에 대한 정보 가져오기
