### ISSUE TITLE
Feat: 관리자가 이메일로 로그인한다

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#37]
### 기능 설명
관리자가 이메일, 패스워드를 통해 로그인하면 관리자 검증 후 토큰 반환

### To-Do
- [x] `amin` 앱 추가 (settings 등록)
- [x] 이메일, 패스워드로 테이블에서 데이터 가져오기
- [x] `is_staff` 확인
- [x] 토큰에 데이터 담기
- [x] 토큰 전달
