### ISSUE TITLE
Chore: 서버 배포를 위한 파일 작성

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#45]
### 기능 설명
프론트와 API 테스트를 위해 테스트용 서버를 NCP로 배포한다.

### To-Do
- [x] uWSGI 설치 및 설정
- [x] Nginx를 위한 proxy 설정
- [x] scripts 추가
- [x] Dockerfile 작성
- [x] 배포와 관리를 위한 docker-compose-deploy.yml 작성

### 기타
- 참고1: [django-backend-youtube2 (김인섭 강사님)](https://github.com/Seopftware/django-backend-youtube2)
- 참고2: [django-backend-youtube2-notion (김인섭 강사님)](https://visioneer.notion.site/4-Deployment_-1-Docker-6532004958604f7d9ec3816f4252d82d)
