### ISSUE TITLE
Feat: 관리자가 식당관리 메인페이지에 접속한다

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#92]
### 기능 설명
식당관리 메인페이지에 접속하면 입점되어있는 식당들 리스트가 화면에 표시된다.
리스트를 화면에 표시할 수 있도록 해당 데이터를 넘겨주는 API 개발

### To-Do
- [x] API url에 등록 ([GET], '/api/v1/admin/restaurant/list')
- [x] DB에서 메인화면에 표시될 정보 가져오기
- [x] JSON 형식으로 리턴
