### ISSUE TITLE
Feat: 가게조회 API response 데이터 추가

### ISSUE THREAD

**Issue by newbission** [OZ-Coding-School/oz_02_collabo-005-BE#95]
### 기능 설명
가게조회시 오픈/클로즈 시간, 오픈 상태, 메뉴별 품절 여부를 데이터에 추가

### To-Do
- [x] 오픈/클로즈 시간, 오픈 상태를 가게 데이터에 추가
- [x] 메뉴별 품절 여부를 메뉴별 데이터에 추가
- [x] 가게리스트 조회시 데이터에 오픈 상태 여부 추가
